from __future__ import annotations

from life_report.pipeline_defaults import (
    DEFAULT_AUDIO_CONCURRENCY,
    DEFAULT_COMIC_IMAGE_MODEL,
    DEFAULT_COMIC_MAX_PANELS,
    DEFAULT_HIGHLIGHT_MAX_SEGMENTS,
    DEFAULT_HIGHLIGHT_TARGET_SECONDS,
    DEFAULT_STORY_TEXT_MODEL,
    DEFAULT_SUMMARY_TEXT_MODEL,
    DEFAULT_VIDEO_CONCURRENCY,
)


DESKTOP_DEFAULT_SUMMARY_MODEL = DEFAULT_SUMMARY_TEXT_MODEL
DESKTOP_DEFAULT_STORY_MODEL = DEFAULT_STORY_TEXT_MODEL
DESKTOP_DEFAULT_COMIC_IMAGE_MODEL = DEFAULT_COMIC_IMAGE_MODEL
DESKTOP_DEFAULT_COMIC_MAX_PANELS = DEFAULT_COMIC_MAX_PANELS
DESKTOP_DEFAULT_HIGHLIGHT_TARGET_SECONDS = DEFAULT_HIGHLIGHT_TARGET_SECONDS
DESKTOP_DEFAULT_HIGHLIGHT_MAX_SEGMENTS = DEFAULT_HIGHLIGHT_MAX_SEGMENTS
DESKTOP_DEFAULT_AUDIO_CONCURRENCY = DEFAULT_AUDIO_CONCURRENCY
DESKTOP_DEFAULT_VIDEO_CONCURRENCY = DEFAULT_VIDEO_CONCURRENCY


def desktop_concurrency_options() -> list[str]:
    highest = max(
        DESKTOP_DEFAULT_AUDIO_CONCURRENCY,
        DESKTOP_DEFAULT_VIDEO_CONCURRENCY,
        4,
    )
    return [str(item) for item in range(1, highest + 1)]
